### ISSUE TITLE
multi-monitor support snap

### ISSUE THREAD

**Issue by Goldman90** [jairocontreras/ahk#1]
hey, is there any chance to add multi-monitor support to snap?

**Comment by jairocontreras** [comment]
great idea! i'll look into it as soon as possible but right now development is paused for some time. thanks for your interest!

**Comment by jairocontreras** [comment]
i created an alternate version [here](https://github.com/jairocontreras/autohotkey/blob/master/archive/snap%20(multi-monitor).ahk). supports a dual monitor setup with the same screen resolution
